/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventDashboardRouteImport } from './routes/$event/dashboard'
import { Route as EventDashboardIndexRouteImport } from './routes/$event/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDashboardRoute = EventDashboardRouteImport.update({
  id: '/$event/dashboard',
  path: '/$event/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDashboardIndexRoute = EventDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$event/dashboard': typeof EventDashboardRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/events': typeof EventsIndexRoute
  '/$event/dashboard/': typeof EventDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events': typeof EventsIndexRoute
  '/$event/dashboard': typeof EventDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$event/dashboard': typeof EventDashboardRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/events/': typeof EventsIndexRoute
  '/$event/dashboard/': typeof EventDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$event/dashboard'
    | '/events/create'
    | '/events'
    | '/$event/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/create' | '/events' | '/$event/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$event/dashboard'
    | '/events/create'
    | '/events/'
    | '/$event/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventDashboardRoute: typeof EventDashboardRouteWithChildren
  EventsCreateRoute: typeof EventsCreateRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$event/dashboard': {
      id: '/$event/dashboard'
      path: '/$event/dashboard'
      fullPath: '/$event/dashboard'
      preLoaderRoute: typeof EventDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$event/dashboard/': {
      id: '/$event/dashboard/'
      path: '/'
      fullPath: '/$event/dashboard/'
      preLoaderRoute: typeof EventDashboardIndexRouteImport
      parentRoute: typeof EventDashboardRoute
    }
  }
}

interface EventDashboardRouteChildren {
  EventDashboardIndexRoute: typeof EventDashboardIndexRoute
}

const EventDashboardRouteChildren: EventDashboardRouteChildren = {
  EventDashboardIndexRoute: EventDashboardIndexRoute,
}

const EventDashboardRouteWithChildren = EventDashboardRoute._addFileChildren(
  EventDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventDashboardRoute: EventDashboardRouteWithChildren,
  EventsCreateRoute: EventsCreateRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
